
zad1: zad1.cpp
	g++ zad1.cpp biblioteka.cpp -O2 -o zad1 -std=c++20

zad2: zad2.cpp
	g++ zad2.cpp biblioteka.cpp -O2 -o zad2 -std=c++20

zad3: zad3.cpp
	g++ zad3.cpp biblioteka.cpp -O2 -o zad3 -std=c++20

zad4: zad4.cpp
	g++ zad4.cpp biblioteka.cpp -O2 -o zad4 -std=c++20

zad5: zad5.cpp
	g++ zad5.cpp biblioteka.cpp -O2 -o zad5 -std=c++20

zad6: zad6.cpp
	g++ zad6.cpp biblioteka.cpp -O2 -o zad6 -std=c++20

zad7: zad7.cpp
	g++ zad7.cpp biblioteka.cpp -O1 -o zad7 -std=c++20

zad8: zad8.cpp
	g++ zad8.cpp biblioteka.cpp -O2 -o zad8 -std=c++20

clean:
	rm -f zad1 zad2 zad3 zad4 zad5 zad6 zad7 zad8
